PROJECT_NAME := hello_world_zturn

M_DEPS += ../../common/zturn/zturn_system_ps7.tcl
M_DEPS += ../../common/zturn/zturn_system_constr.xdc
M_DEPS += ../../common/zturn/zturn_system_bd.tcl
M_DEPS += ../../../library/xilinx/common/ad_iobuf.v

include ../../scripts/project-xilinx.mk
